@01_schema.sql
@02_sequences_triggers.sql
@03_pkg_users.sql
@04_pkg_appointments.sql
@05_pkg_pharmacy.sql
@06_pkg_ambulance.sql
@09_pkg_facilities.sql
@10_pkg_inventory.sql
@11_pkg_search.sql
@12_pkg_filters.sql
@07_seed_data.sql
exit
